services:
  # Servicio para el Backend y Frontend unificado
  - type: web
    name: ai-course-finder
    env: python
    region: ohio # O la más cercana a ti
    plan: free
    # IMPORTANTE: Aquí le decimos que instale desde la carpeta backend
    buildCommand: pip install -r backend/requirements.txt
    # Iniciamos desde la carpeta backend y enlazamos el puerto
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
     # - fromGroup: ai-course-config # Grupo de variables que crearemos luego
