services:
  - type: web
    name: ai-course-finder
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
        required: truex
